export const UPDATE_DIRECTORY_CONTENT = "DIRECTORY_CONTENT";
export const DIR_CONTENT_REQUEST      = "DIR_CONTENT_REQUEST";

export const OPEN_FILE_REQUEST   = "OPEN_FILE_REQUEST";
export const CLOSE_FILE_REQUEST  = "CLOSE_FILE_REQUEST";
export const SELECT_FILE_REQUEST = "SELECT_FILE_REQUEST";

export const NEW_FILE_CREATED     = "NEW_FILE_CREATED";
export const FILE_CONTENT_REQUEST = "FILE_CONTENT_REQUEST";
export const UPDATE_FILE_CONTENT  = "UPDATE_FILE_CONTENT";